[project]
name = "langgraphnew"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kishanranaghosh", email = "kishanghosh090@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.4.3",
    "langgraph>=1.2.14",
]

[project.scripts]
langgraphnew = "langgraphnew:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
